[platformio]
default_envs = rak4631_fossorial

[rak4631_fossorial]
platform = https://github.com/RAKWireless/WiseDuino.git
board = rak4631
framework = arduino
board_build.mcu = nrf52840
board_build.ldscript = varient/rak4631/ld/rak4631.ld
extra_scripts = post:post_build.py, pre:pre_upload.py
build_flags =
    -std=c++17
    -Wno-unknown-pragmas
    -DMESH_DEBUG=0
    -DFIRMWARE_VERSION="v0.1.0"
    -DFIRMWARE_BUILD_DATE="\"$(shell date +'%d %b %Y')\""
    -DLORA_FREQ=915.0
    -DLORA_BW=250
    -DLORA_SF=10
    -DLORA_CR=5
    -DLORA_TX_POWER=20
    -I examples/fossorial_gopher
    -I examples/fossorial_gopher/include
src_filter = +<examples/fossorial_gopher/> -<.>

lib_deps =
    RTC
    RADIOLIB
    bblanchon/ArduinoJson
    adafruit/Adafruit TinyUSB Library

[rak4631_fossorial_eu868]
board = rak4631
build_flags =
    ${rak4631_fossorial.build_flags}
    -DLORA_FREQ=868.0
